#include <UGL/Program.h>

#include <iostream>

using namespace Ubpa;
using namespace Ubpa::gl;
using namespace std;


Program::Program(const GLchar* vs_src, const GLchar* fs_src) : Program{
	Shader{Shader::Type::VERTEX, vs_src},
	Shader{Shader::Type::FRAGMENT, fs_src}
} {}

Program::Program(Shader&& vs_, Shader&& fs_)
	: vs(move(vs_)), fs(move(fs_))
{
	ID = gl::CreateProgram();

	if (!IsValid()) {
		cerr << "ERROR::Shader::Shader(Type, const GLchar*):" << endl
			<< "  create program fail" << endl
			<< "  - vs path: " << (vs->path->empty() ? "generated by code / empty" : vs->path.get()) << endl
			<< "  - fs path: " << (fs->path->empty() ? "generated by code / empty" : vs->path.get()) << endl
			<< "  - gs path: " << (gs->path->empty() ? "generated by code / empty" : vs->path.get()) << endl;
		return;
	}

	gl::AttachShader(ID, vs->ID);
	gl::AttachShader(ID, fs->ID);

	gl::LinkProgram(ID);
}

bool Program::CheckLinkError() const {
	assert(IsValid());

	GLint success;
	gl::GetProgramiv(ID, GL_LINK_STATUS, &success);
	if (success)
		return true;

	// link fail
	constexpr GLsizei infoLen = 512;
	GLchar infoLog[infoLen];
	gl::GetShaderInfoLog(ID, infoLen, NULL, infoLog);
	cerr << "ERROR::Shader::CheckCompileError():" << endl
		<< "  link fail" << endl
		<< "  - vs path: " << (vs->path->empty() ? "generated by code / empty" : vs->path.get()) << endl
		<< "  - fs path: " << (fs->path->empty() ? "generated by code / empty" : vs->path.get()) << endl
		<< "  - gs path: " << (gs->path->empty() ? "generated by code / empty" : vs->path.get()) << endl
		<< "  - info: " << infoLog << endl;
	return false;
}

void Program::Use() const {
	assert(IsValid());
	gl::UseProgram(ID);
}
